services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: app
    volumes:
      - .:/var/www:cached
      - ./storage:/var/www/storage
      - ./vendor:/var/www/vendor
    environment:
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG}
      APP_KEY: ${APP_KEY}
    depends_on:
      - db
      - redis
    networks:
      - laravel

  horizon:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: horizon
    command: php artisan horizon
    volumes:
      - .:/var/www:cached
      - ./vendor:/var/www/vendor
      - ./storage:/var/www/storage
    depends_on:
      - app
      - redis
    networks:
      - laravel

  webserver:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www:cached
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: postgres:15
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - laravel

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - laravel

networks:
  laravel:

volumes:
  pgdata: